'use strict';

var RPS_MOVES = {
  ROCK: 'ROCK',
  PAPER: 'PAPER',
  SCISSOR: 'SCISSOR'
};

var RPS_MOVE_NAMES = Object.keys(RPS_MOVES);

var RPS_BREAKING_MOVES = {
  ROCK: RPS_MOVES.PAPER,
  PAPER: RPS_MOVES.SCISSOR,
  SCISSOR: RPS_MOVES.ROCK
};

module.exports = {
  RPS_MOVES: RPS_MOVES,
  RPS_MOVE_NAMES: RPS_MOVE_NAMES,
  RPS_BREAKING_MOVES: RPS_BREAKING_MOVES
};